name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: yj971020/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 3ab9b6fcdcda8f98fd4c13bd2527b3ed
          TIMEZONE: Asia/Seoul
